p8105_hw2_zc2959
================
Zhenghong Chen zc2959
2026-10-06

# Problem 1

## NYC Subway Data

``` r
transit_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data - NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude, route1:route11, entrance_type, entry, vending, ada) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

### Subway Data Description

1.  `transit_df` has 1868 rows and 19 columns, with each row
    representing one subway entrance or exit.

2.  The data include the station, line, location, routes served,
    entrance type, entry, vending, and ADA status. I kept the columns
    needed for the analysis and changed `entry` from YES / NO to TRUE /
    FALSE.

3.  The data are not tidy yet because the route information is spread
    across `route1` to `route11`.

## Subway Stations

``` r
n_stations = 
  transit_df |>
  distinct(line, station_name) |>
  nrow()

n_ada = 
  transit_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()

entry_prop = 
  transit_df |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

1.  There are 465 distinct stations.

2.  84 stations are ADA compliant.

3.  37.70492% of station entrances / exits without vending allow
    entrance.

## Reformatting data

``` r
transit_long = 
  transit_df |>
  mutate(
    across(route1:route11, as.character)
  ) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )
```

``` r
n_a_stations = 
  transit_long |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()

n_a_ada = 
  transit_long |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

1.  The A train serves 60 distinct stations.

2.  17 of the stations served by the A train are ADA compliant.

# Problem 2

``` r
library(readxl)
```

## Trash Wheel Data

``` r
mr_trash = 
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    sports_balls = as.integer(round(sports_balls)),
    wheel = "Mr. Trash Wheel"
  )

head(mr_trash, 5)
```

    ## # A tibble: 5 × 15
    ##   dumpster month  year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, wheel <chr>

``` r
names(mr_trash)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "plastic_bags"       "wrappers"          
    ## [13] "sports_balls"       "homes_powered"      "wheel"

``` r
dim(mr_trash)
```

    ## [1] 740  15

### Mr. Trash Wheel Description

1.  The Mr. Trash Wheel data have 740 observations after removing rows
    without dumpster data.

2.  The variable names were cleaned using `clean_names()`.

3.  `sports_balls` was rounded to the nearest whole number and converted
    to an integer.

## Professor Trash Wheel and Gwynnda

``` r
prof_trash = 
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    na = "dive"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    wheel = "Professor Trash Wheel"
  )

gwynnda_trash = 
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    wheel = "Gwynnda"
  )

head(prof_trash, 5)
```

    ## # A tibble: 5 × 14
    ##   dumpster month     year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr>    <int> <dttm>                    <dbl>              <dbl>
    ## 1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ## 2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ## 3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ## 4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ## 5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, wheel <chr>

``` r
head(gwynnda_trash, 5)
```

    ## # A tibble: 5 × 13
    ##   dumpster month  year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ## 1        1 July   2021 2021-07-03 00:00:00        0.93                 15
    ## 2        2 July   2021 2021-07-07 00:00:00        2.26                 15
    ## 3        3 July   2021 2021-07-07 00:00:00        1.62                 15
    ## 4        4 July   2021 2021-07-16 00:00:00        1.76                 15
    ## 5        5 July   2021 2021-07-30 00:00:00        1.53                 15
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, wheel <chr>

``` r
dim(prof_trash)
```

    ## [1] 137  14

``` r
dim(gwynnda_trash)
```

    ## [1] 392  13

The Professor Trash Wheel and Gwynnda data are cleaned in the same way,
and `wheel` is added to identify the source of each observation.

## Combining Trash Wheel Data

``` r
trash_wheel = 
  bind_rows(
    mr_trash,
    prof_trash,
    gwynnda_trash
  ) |>
  select(wheel, everything())

head(trash_wheel, 5)
```

    ## # A tibble: 5 × 15
    ##   wheel  dumpster month  year date                weight_tons volume_cubic_yards
    ##   <chr>     <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ## 1 Mr. T…        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2 Mr. T…        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3 Mr. T…        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4 Mr. T…        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5 Mr. T…        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

``` r
dim(trash_wheel)
```

    ## [1] 1269   15

``` r
trash_wheel |>
  select(
    wheel, dumpster, month, year,
    weight_tons, volume_cubic_yards,
    plastic_bottles, cigarette_butts
  ) |>
  head(10)
```

    ## # A tibble: 10 × 8
    ##    wheel     dumpster month  year weight_tons volume_cubic_yards plastic_bottles
    ##    <chr>        <dbl> <chr> <int>       <dbl>              <dbl>           <dbl>
    ##  1 Mr. Tras…        1 May    2014        4.31                 18            1450
    ##  2 Mr. Tras…        2 May    2014        2.74                 13            1120
    ##  3 Mr. Tras…        3 May    2014        3.45                 15            2450
    ##  4 Mr. Tras…        4 May    2014        3.1                  15            2380
    ##  5 Mr. Tras…        5 May    2014        4.06                 18             980
    ##  6 Mr. Tras…        6 May    2014        2.71                 13            1430
    ##  7 Mr. Tras…        7 May    2014        1.91                  8             910
    ##  8 Mr. Tras…        8 May    2014        3.7                  16            3580
    ##  9 Mr. Tras…        9 June   2014        2.52                 14            2400
    ## 10 Mr. Tras…       10 June   2014        3.76                 18            1340
    ## # ℹ 1 more variable: cigarette_butts <dbl>

### Trash Wheel Data Description

1.  Before combining the data, Mr. Trash Wheel has 740 observations,
    Professor Trash Wheel has 137 observations, and Gwynnda has 392
    observations. After using `bind_rows()`, the combined `trash_wheel`
    dataset has 1269 observations, with each row representing one
    dumpster collection.

2.  The combined dataset includes key variables such as `wheel`,
    `dumpster`, `month`, `year`, `weight_tons`, `volume_cubic_yards`,
    `plastic_bottles`, and `cigarette_butts`. The `wheel` variable shows
    which Trash Wheel each observation comes from, while the other
    variables describe when the dumpster was collected and the amount or
    type of trash collected.

3.  After combining the three datasets, observations from all three
    Trash Wheels are stored in the same dataframe. Variables with the
    same name are combined into the same columns, while variables that
    were not recorded for every Trash Wheel contain missing values for
    those observations.
